# numpy arrays

* Lets consider a traditional way of writing an array !!

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

* The above is the way, that the traditional array works

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

* There above we casted the my_list normal array, to the numpy array() function

In [7]:
"#NOTE, That above provides us with a 1-D array"

'#NOTE, That above provides us with a 1-D array'

* For a list of multi-dimensional array,here we do the following....

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
numpy_my_mat = np.array(my_mat)

In [10]:
print(my_mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [11]:
numpy_my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


##### Thats what occurs on casting normal pyhton list to numpy arrays


## Common ways of creating numpy arrays 

In [12]:
np.arange(0,90,30)

array([ 0, 30, 60])

~Here the syntax is as follows :-

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Raise of pure zeros in an array


* if you want to generate an array of zeros,then the function ###.zeros()

In [23]:
np.zeros(3)

array([0., 0., 0.])

#### Raise of pure zeros in a multi-dimensional array

In [18]:
np.zeros((8,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### Raise of pure ones in 1-D array

* Here we use numpy.ones() function to generate pure ones in a single dimensional arrays

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Raise of pure ones in Multi-dimensional arrays

* Here we use the the function np.ones((rows,column)) to generate that arrays

In [27]:
np.ones((8,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* These arrays can even be stored in a variable and then printed put in one line

In [28]:
my_ones = np.ones((8,4))

In [29]:
print(my_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## linspace()

* This python method is used to devide equaly a range of values provided in the argument section

In [4]:
"""
Consider the following example bellow :
"""
import numpy as np

In [31]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [5]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

### Creating an Identity Matrix using numpy

* Here we use np.eye(rows), this means it will create a matrix of row-dimensional array

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Creating Arrays of random numbers

* In order to achieve this random generation, we use np.random.random_method()

#### np.random.rand()

In [38]:
np.random.rand(5)

array([0.9208251 , 0.07354636, 0.29941574, 0.41854818, 0.96087478])

* NOTE, here the rand() method is used to generate numbers from zero to one, with the division to mach the equal division of the passed argument

In [40]:
np.random.rand(10)

array([0.57752835, 0.74184354, 0.34777901, 0.15312769, 0.05893568,
       0.83296398, 0.80591741, 0.9481664 , 0.08245793, 0.9642945 ])

* for a multi-dimensional array of random generation of numbers

In [42]:
np.random.rand(5,5)

array([[0.47344357, 0.35657005, 0.22146007, 0.3926975 , 0.0220497 ],
       [0.35628378, 0.36854497, 0.38785054, 0.90168194, 0.19586962],
       [0.81264171, 0.58602759, 0.80921437, 0.56031496, 0.76978661],
       [0.86274356, 0.65534464, 0.37597625, 0.46565515, 0.88547072],
       [0.64330691, 0.27676929, 0.27884037, 0.08117995, 0.31036532]])

#### np.random.randn()

* At this point, we can generate numbers from a standard normal distribution, totaly random

In [44]:
np.random.randn(8)

array([ 0.65738897, -0.5058676 , -1.05286314, -0.29413583,  0.60326728,
       -0.85250294,  0.84250319, -0.29389281])

In [45]:
np.random.randn(5,5)

array([[-0.44570379, -0.66679834, -0.02325141, -0.10274203, -0.0832821 ],
       [ 1.99367636,  0.84226416,  0.2302015 , -0.00275894, -0.2890331 ],
       [ 1.40376746, -0.01761842,  2.15502673,  2.08696672, -0.10172507],
       [-0.67347879, -0.99582894, -1.41247058,  1.34275669, -0.0637396 ],
       [-0.17992378, -0.980505  , -0.3432044 , -1.98833427, -1.04551416]])

#### np.random.randint()

* Now here what happens is, we're going to generate random numbers from a lower to a higher level, totally random

In [46]:
np.random.randint(1,100)

64

In [47]:
np.random.randint(1,20)

10

* Now incase you need the size of your array, to be more than one number, then we pass the third argument in our function

In [48]:
np.random.randint(1,20,20)

array([10, 16, 12, 11,  3,  2, 19, 18,  6,  4, 14,  9,  1, 11, 14,  3, 19,
        1, 16,  5])

In [49]:
np.random.randint(1,100,10)

array([47, 12, 89, 74, 21, 66, 11, 21, 53, 56])

In [50]:
np.random.randint(1,200,3)

array([106, 161,  12])

## Atributes and methods of an array

* Now am going to create different arrays in order to demostrate new examples of this part 

In [51]:
arr = np.arange(25)

In [52]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [55]:
ranarr = np.random.randint(0,50,10)

In [56]:
ranarr

array([21, 19, 30, 36,  4,  2, 23, 38,  6, 21])

#### reshape() method

* This will essentially, help to return the same data, but with a new shape

In [57]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

* So what happened above is that, we reshaped the same data from 0-24, making it a 5 by 5 array

* Special Note to make is that, the array should be filled out

# NumPy indexing and Selection

In [58]:
import numpy as np

* generating my sample array

In [62]:
arr = np.arange(0,11)

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* In order to index we're going to do as follows 

In [63]:
arr[8]

8

* if i want to get the values of arr in range, i have to use slicing notations

In [64]:
arr[2:5]

array([2, 3, 4])

In [65]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* Its just that much simple

#### Numpy array, differs from python arrays, due to their ability to broadcast

###### numpy arrays broadcasting

* Broadcasting of numpy arrays, means changing all values of an array, depending on the selection

In [66]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* Now if i want to change the first 5, digits to a specific uniform value, that's called broadcasting

* consider :

In [69]:
arr[0:5] = 100

In [70]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

* Reseting the array,again for a different example, we get .....

In [72]:
arr=np.arange(0,21)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [74]:
first_slice_arr = arr[0:11]

In [75]:
first_slice_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* Now i want to broadcast 70 to half of the first slice array 

In [76]:
first_slice_arr[1:5] = 70

In [77]:
first_slice_arr

array([ 0, 70, 70, 70, 70,  5,  6,  7,  8,  9, 10])

* Now our second slice array ---

In [78]:
second_slice_arr = arr[11:21]

In [79]:
second_slice_arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

* now i want to broadcast, the number 50, to the last 5 digits of the arr

In [80]:
second_slice_arr[:5]= 20

In [81]:
second_slice_arr


array([20, 20, 20, 20, 20, 16, 17, 18, 19, 20])

* Now that is broadcasting

In [82]:
arr

array([ 0, 70, 70, 70, 70,  5,  6,  7,  8,  9, 10, 20, 20, 20, 20, 20, 16,
       17, 18, 19, 20])

* Just note that, these array broadcasting creates a change not only to the sliced variables, but also to the olriginal arrays

* Now in order for me to copy an array,i can specify the keyname copy from numpy

In [83]:
arr_copy = arr.copy()

In [84]:
arr_copy

array([ 0, 70, 70, 70, 70,  5,  6,  7,  8,  9, 10, 20, 20, 20, 20, 20, 16,
       17, 18, 19, 20])

* So normaly, the good thing about specifying the copy keyword, is that, even when i broadcas again, my original array, doesn't get affected 

In [85]:
arr

array([ 0, 70, 70, 70, 70,  5,  6,  7,  8,  9, 10, 20, 20, 20, 20, 20, 16,
       17, 18, 19, 20])

In [86]:
arr_copy

array([ 0, 70, 70, 70, 70,  5,  6,  7,  8,  9, 10, 20, 20, 20, 20, 20, 16,
       17, 18, 19, 20])

* Now am broadcasting to the copy of the original arr, and i need to see if the original array will get affected 

In [87]:
arr_copy[:]=100

In [88]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100])

* Now, let's check the original copy

### Indexing a 2-D array using numpy arrays 

In [89]:
import numpy as np

In [90]:
arr_2d = np.array([[1,2,3],[4,5,6],[70,23,45]])

In [91]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [70, 23, 45]])

* now, i want to grab a digit 5

In [93]:
arr_2d[0][0]

1

In [94]:
arr_2d[1][1]

5

In [95]:
arr_2d[2][2]

45

* Now, the recomended way, of accessing elements in multi-dimensional array, is by using single bracket notation 

* So for example, like the last example with double bracket notation

In [96]:
arr_2d[2,2]

45

#### sub matrixes of the array

In [98]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [70, 23, 45]])

* Now we want to grab element up to the second row, and you want only the values of the second and third columns

In [100]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

* Where the first argement deals with the selection of the rows,and the second argument deals with the selection of the columns in the arr_2d matrix

* Now incase we want to grab the from the second row going downwards, what we do is:
    

In [103]:
arr_2d[1:]

array([[ 4,  5,  6],
       [70, 23, 45]])

In [104]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

## Conditional selection

* Now i'll create a single dimension array, a simple one ofcourse

In [105]:
array = np.arange(1,11)

In [107]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* Now we can compare this whole list by passing to conditional operators and return some boolean values

In [108]:
array>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

* we can also store the produced boolean array. Let's try that 

In [112]:
bool_array = array>5

In [113]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

* In order to get what happened to be true, we can pass the boolean array, within the original array 

In [114]:
array[bool_array]

array([ 6,  7,  8,  9, 10])

* alternatively, we can do it in one line of code 

In [115]:
array[array<9]

array([1, 2, 3, 4, 5, 6, 7, 8])

* The above method will work, but the only disadvantage is that,you wont be able to have the boolean array no more 

### Simple indexing and selection exercise 

In [116]:
arr_d = np.arange(50).reshape(5,10)

In [121]:
arr_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [119]:
arr_d[1,2:7]

array([12, 13, 14, 15, 16])

In [120]:
arr_d[:4,2:6]

array([[ 2,  3,  4,  5],
       [12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35]])

<h1 align = "center">NumPy Operations</h1>
<ul align = "center">
    <li> Arrays with Array </li>
    <li> Arrays with Scalars </li>
    <li> Universal Array functions </li>
</ul>
</div>

In [122]:
import numpy as np

In [123]:
arr = np.arange(0,11)

In [124]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Array addition

In [126]:
total_array = arr+arr

In [127]:
total_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [130]:
array_total_copy = np.copy(total_array)

In [131]:
array_total_copy

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [132]:
array_total_copy[:6] = 1

In [138]:
array_total_copy

array([ 1,  1,  1,  1,  1,  1, 12, 14, 16, 18, 20])

### Array subtraction

* Now for array, substraction

In [136]:
total_array - array_total_copy

array([-1,  1,  3,  5,  7,  9,  0,  0,  0,  0,  0])

* Now we can see the above is the results of the results of the minus operator

### Array Multiplication

In [140]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### ---> Now  we want here the numbers are broadcasted in order to create multiples in a sequential manner

* that is 

In [141]:
    arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

* Now we will store that answer to our new variable

In [145]:
our_test = arr * 100

In [146]:
our_test

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [148]:
arr/our_test

<ipython-input-148-6fd5cb172bf9>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/our_test


array([ nan, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01])

* The man means ther is a ZeroDivisionError,but numpy doesn't give an error to us 


<h2 align= "center"> Universal Array Functions </h2>

#### The square root

* consider the following generated array

In [155]:

new_array= np.arange(40,70)

In [156]:
new_array

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [157]:
np.sqrt(new_array)

array([6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386])

#### The exponential that XP

In [158]:
np.exp(new_array)

array([2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22,
       3.83100800e+22, 1.04137594e+23, 2.83075330e+23, 7.69478527e+23,
       2.09165950e+24, 5.68572000e+24, 1.54553894e+25, 4.20121040e+25,
       1.14200739e+26, 3.10429794e+26, 8.43835667e+26, 2.29378316e+27,
       6.23514908e+27, 1.69488924e+28, 4.60718663e+28, 1.25236317e+29,
       3.40427605e+29, 9.25378173e+29])

#### For the max value 

In [160]:
new_array.max()

69

#### For min value

In [161]:
new_array.min()

40

#### For Trig Functions

In [163]:
np.sin(new_array)

array([ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
        0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265,
       -0.26237485,  0.67022918,  0.98662759,  0.39592515, -0.55878905,
       -0.99975517, -0.521551  ,  0.43616476,  0.99287265,  0.63673801,
       -0.30481062, -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,
        0.82682868, -0.02655115, -0.85551998, -0.89792768, -0.11478481])

In [164]:
np.cos(new_array)

array([-0.66693806, -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,
        0.52532199, -0.43217794, -0.99233547, -0.64014434,  0.30059254,
        0.96496603,  0.7421542 , -0.16299078, -0.91828279, -0.82930983,
        0.02212676,  0.85322011,  0.89986683,  0.11918014, -0.77108022,
       -0.95241298, -0.25810164,  0.67350716,  0.98589658,  0.39185723,
       -0.56245385, -0.99964746, -0.5177698 ,  0.44014302,  0.99339038])

In [165]:
np.tan(new_array)

array([-1.11721493e+00,  1.60656699e-01,  2.29138799e+00, -1.49838734e+00,
        1.77046993e-02,  1.61977519e+00, -2.08661353e+00, -1.24527568e-01,
        1.20012724e+00, -3.17290855e+00, -2.71900612e-01,  9.03086149e-01,
       -6.05327238e+00, -4.31158197e-01,  6.73800101e-01, -4.51830879e+01,
       -6.11273688e-01,  4.84699227e-01,  8.33085685e+00, -8.25774009e-01,
        3.20040389e-01,  3.74316794e+00, -1.09750978e+00,  1.69749752e-01,
        2.34786031e+00, -1.47003826e+00,  2.65605178e-02,  1.65231726e+00,
       -2.04008160e+00, -1.15548546e-01])